import turtle
import random


turtle.screensize(500,500)
turtle.pendown()
turtle.circle(1,90)
turtle.circle(1,90)
turtle.speed(9999999)
d=0
c=0
a=1
b=1
a=a+b
b=a+b
while a>0:
    turtle.circle(a,10)
    turtle.color("green")
    turtle.circle(a,10)
    turtle.color("red")
    turtle.circle(a,10)
    turtle.color("blue")
    turtle.circle(a,10)
    turtle.color("yellow")
    turtle.circle(a,10)
    turtle.color("purple")
    turtle.circle(a,10)
    turtle.color("cyan")
    turtle.circle(a,10)
    turtle.color("pink")
    turtle.circle(a,10)
    turtle.color("brown")
    turtle.circle(a,10)
    turtle.color("black")
    turtle.circle(b,10)
    turtle.color("green")
    turtle.circle(b,10)
    turtle.color("red")
    turtle.circle(b,10)
    turtle.color("blue")
    turtle.circle(b,10)
    turtle.color("yellow")
    turtle.circle(b,10)
    turtle.color("purple")
    turtle.circle(b,10)
    turtle.color("cyan")
    turtle.circle(b,10)
    turtle.color("pink")
    turtle.circle(b,10)
    turtle.color("brown")
    turtle.circle(b,10)
    turtle.color("black")
    a=a+b
    b=a+b
    if a>240:
        break
turtle.setx(400)
turtle.sety(400)
turtle.speed(200000)
while c==0:
    turtle.forward(50)
    'turtle.color("green")'
    turtle.forward(50)
    'turtle.color("red")'
    turtle.forward(50)
    'turtle.color("blue")'
    turtle.forward(50)
    'turtle.color("yellow")'
    turtle.forward(50)
    'turtle.color("purple")'
    turtle.forward(50)
    'turtle.color("cyan")'
    turtle.forward(50)
    'turtle.color("pink")'
    turtle.forward(50)
    'turtle.color("brown")'
    turtle.forward(50)
    'turtle.color("orange")'
    turtle.forward(50)
    'turtle.color("black")'

    turtle.forward(50)
    'turtle.color("green")'
    turtle.forward(50)
    'turtle.color("red")'
    turtle.forward(50)
    'turtle.color("blue")'
    turtle.forward(50)
    'turtle.color("yellow")'
    turtle.forward(50)
    'turtle.color("purple")'
    turtle.forward(50)
    'turtle.color("cyan")'
    turtle.forward(50)
    'turtle.color("pink")'
    turtle.forward(50)
    'turtle.color("brown")'
    turtle.forward(50)
    'turtle.color("orange")'
    turtle.forward(50)
    'turtle.color("black")'


    turtle.left(90)
    turtle.forward(2)
    turtle.left(90)
    d=d+1
    
    turtle.forward(50)
    'turtle.color("green")'
    turtle.forward(50)
    'turtle.color("red")'
    turtle.forward(50)
    'turtle.color("blue")'
    turtle.forward(50)
    'turtle.color("yellow")'
    turtle.forward(50)
    'turtle.color("purple")'
    turtle.forward(50)
    'turtle.color("cyan")'
    turtle.forward(50)
    'turtle.color("pink")'
    turtle.forward(50)
    'turtle.color("brown")'
    turtle.forward(50)
    'turtle.color("orange")'
    turtle.forward(50)
    'turtle.color("black")'

    turtle.forward(50)
    'turtle.color("green")'
    turtle.forward(50)
    'turtle.color("red")'
    turtle.forward(50)
    'turtle.color("blue")'
    turtle.forward(50)
    'turtle.color("yellow")'
    turtle.forward(50)
    'turtle.color("purple")'
    turtle.forward(50)
    'turtle.color("cyan")'
    turtle.forward(50)
    'turtle.color("pink")'
    turtle.forward(50)
    'turtle.color("brown")'
    turtle.forward(50)
    'turtle.color("orange")'
    turtle.forward(50)
    'turtle.color("black")'

    turtle.left(-90)
    turtle.forward(2)
    turtle.left(-90)
    d=d+1
    if d==200:
        break
d=0
while d!=200:
    turtle.left(90)
    turtle.forward(400)
    turtle.left(-90)
    turtle.forward(2)
    turtle.left(-90)
    turtle.forward(400)
    turtle.left(90)
turtle.setx(0)
turtle.sety(0)
